/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "ClipSoftly.h"
#include "Focus.h"
#include "Logical4.h"
#include "Mojo.h"
#include "Point.h"
#include "Pressure5.h"
#include "Transient.h"
#include "Tube2.h"

// Include compiled network files ------------------

#include "Boxer.h"
#include "Karate.h"
#include "Sumo.h"
#include "wtf.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

